extends: airbnb-base
env:
  node: true
  mocha: true
  es6: true
globals:
  window: true
parser: typescript-eslint-parser
parserOptions:
  sourceType: module
  ecmaFeatures: 
    modules: true
rules:
  no-console: off
  no-param-reassign: off
  no-new-func: off